services:
    cf_frontend:
        container_name: "cf_frontend"
        build:
            context: .
            dockerfile: ./config/develop/docker/Dockerfile
        restart: always
        tty: true
        stdin_open: true
        ports:
            - "8000:3000"
            - "9000:4000"
        volumes:
            - .:/app
            - ./node_modules:/app/node_modules
